CREATE ROLE kolpomail WITH
    LOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    NOREPLICATION
    NOBYPASSRLS
    PASSWORD 'kolpomail';

CREATE DATABASE kolpomail
    WITH
    OWNER = kolpomail
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    IS_TEMPLATE = False;
